### ISSUE TITLE
关于hexo-theme-cards的一些疑问

### ISSUE THREAD

**Issue by GhDemi** [Alendia/Alendia#1]
你好，我也是cards主题的一个使用者，但是我不知道如何设置首页的背景图以及文章最后如图所示的内容
![image](https://user-images.githubusercontent.com/96169594/162354915-51352397-ef72-4b09-bef4-8ba7acbf31bc.png)
在网上找了一些方法但是依旧没有解决问题，我觉得你的blog设置的非常nice所以想向你求救。

不胜感激！！！

**Comment by Alendia** [comment]
首页的背景图是我自己对 Cards 的源代码进行了修改，增加了这个进去，如果你不懂如何写 CSS，个人推荐使用含有背景图的类似主题，例如 [Fluid](https://fluid-dev.github.io/hexo-fluid-docs/guide/#%E5%85%B3%E4%BA%8E%E6%8C%87%E5%8D%97)。具体的实现如下：
在 `cover.styl` 中，
```diff
 .cover 
     display block
     text-align center
     margin 3rem auto
+    margin-top 1rem
+    padding 10rem 0
+    background-image url(/back1.png)
+    background-size 100% auto
+    background-repeat no-repeat
+    background-position 50% 50%
+    background-size cover
+    opacity 85%
+    border-radius $radius_main
+    box-shadow 1px 1px 5px 0 rgba(0,0,0,.02),1px 1px 15px 0 rgba(0,0,0,.03)
```
底部的信息在 `themes/cards/_config.yml` 中的 `copyright.custom_text` 中自行添加。
虽然我隐藏了 blog repo 导致无法在对应位置开 issue，但是也不建议在 profile repo 这里开呢。有问题可以私聊我。联系方式可以从 blog About 找到 Telegram Channel，Channel 的 Description 上面有私聊我的方式，或者查看我的 commit 获取邮箱信息。
